"use client";
//import type { Metadata } from "next";
import QueryProvider from "@/components/QueryProvider";
import { SessionProvider } from "next-auth/react";
import { DM_Sans, Geist, Geist_Mono,Open_Sans,Space_Grotesk } from "next/font/google";
import { ToastContainer} from "react-toastify";

import "./globals.css";
import { Suspense, useEffect } from "react";
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const dmSans = DM_Sans({ variable: "--font-dm-sans", subsets: ["latin"], weight: ["300", "400", "500", "700"] });
const openSans = Open_Sans({ variable: "--font-open-sans", subsets: ["latin"], weight: ["300", "400", "600", "800"] });
const spaceGrotesk = Space_Grotesk({ variable: "--font-space-grotesk", subsets: ["latin"], weight: ["300", "400", "500", "700"] });

{
  /*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
}
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // useEffect(()=>{
  //   localStorage.setItem("MealType","1")
  // },[])
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable} ${openSans.variable} ${spaceGrotesk.variable}} antialiased`}
      >
        <ToastContainer/>
        <Suspense
          fallback={
            <div className="w-full h-screen flex justify-center items-center">
              Loading...
            </div>
          }
        >
          <SessionProvider>
            <QueryProvider>
              {children}
            </QueryProvider>
          </SessionProvider>
        </Suspense>
      </body>
    </html>
  );
}
