"use client"
import { Metadata } from "next";
import "./globals.css";

import { QueryClientProvider,QueryClient } from "@tanstack/react-query"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient= new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <QueryClientProvider client={queryClient}>
        {children}
        </QueryClientProvider>
      </body>
    </html>
  );
}
